apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'vault'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
