apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'loki'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
    - namespace: 'monitoring'
      server: '*'
    - namespace: 'opentelemetry-operator-system'
      server: '*'
    - namespace: 'argocd'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'