apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  labels:
    repository: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: "kube-prometheus-stack"
      targetRevision: "58.5.3"
      helm:
          releaseName: kube-prometheus-stack
          valueFiles:
            - $values/charts/monitoring/prometheus-stack-values.yaml
    - repoURL: https://github.com/ahmdsalahme/argocd.git
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=orphan
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
