apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
    {{- .Values.commonLabels | toYaml | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  suspend: {{ .Values.suspend }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .Values.fullnameOverride }}
            image: busybox
            # image: amazon/aws-cli
            # image: mongo:latest
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- if .Values.image.debug }}
            command: ["sleep", "3600"]
            {{- else }}
            command: ["/bin/sh", "-c", "date && sleep 10"]
            {{- end }}