apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  generators:
  - list:
      elements: []
      # - env: env1
  template:
    metadata:
      name: '{{"{{"}}env{{"}}"}}-cert-manager'
    spec:
      project: 'applications'
      source:
        repoURL: 'https://charts.jetstack.io'
        targetRevision: v1.8.2
        chart: cert-manager
        helm:
          values: |
            installCRDs: true
      destination:
        server: https://kubernetes.default.svc
        namespace: cert-manager
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=false