apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-appset
spec:
  generators:
  - list:
      elements: []
  template:
    metadata:
      name: '{{"{{"}}cluster{{"}}"}}-nginx'
    spec:
      project: 'applications'
      source:
        repoURL: https://github.com/ahmdsalahme/argocd.git
        targetRevision: HEAD
        path: releases/applications/web-app
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated: {}