apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-appset
spec:
  generators:
  - list:
      elements:
      - cluster: myapp
        url: https://1.2.3.4
      - cluster: engineering-prod
        url: https://2.4.6.8
      - cluster: finance-preprod
        url: https://9.8.7.6
  template:
    metadata:
      name: '{{"{{"}}cluster{{"}}"}}-nginx'
    spec:
      project: 'applications'
      source:
        repoURL: https://github.com/ahmdsalahme/argocd.git
        targetRevision: HEAD
        path: releases/applications/web-app
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated: {}