apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
  namespace: argocd
  labels:
    repository: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ahmdsalahme/argocd.git
    path: releases/applications/web-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default