apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  labels:
    repository: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: {{ .Values.promtail.targetRevision | quote }}
      helm:
          valueFiles:
            - $values/releases/monitoring/promtail-values.yaml
    - repoURL: https://github.com/ahmdsalahme/argocd.git
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=orphan
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
