apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
spec:
  source:
    repoURL: 'https://github.com/ahmdsalahme/argocd'
    targetRevision: HEAD
    path: argocd
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated: {}