apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-example
  namespace: argocd
  labels:
    repository: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmdsalahme/argocd.git
    path: charts/nginx-example
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-example