apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-example
  name: nginx-example-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-example
  type: ClusterIP