apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  labels:
    repository: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/ahmdsalahme/argocd.git
    path: base/monitoring
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated: {}