apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
  namespace: argocd
  labels:
    repository: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmdsalahme/argocd.git
    path: releases/apps/web-app
    targetRevision: HEAD
  destination:
    name: https://kubernetes.default.svc
    namespace: default