apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-example-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # selector:
  #   matchLabels:
  #     pv: local
  # storageClassName: hostpath