name: "PR Compliance Checks"

on:
  pull_request:
    types: ["opened", "reopened", "edited", "synchronize"]
    branches: ["main", "master"]
    
jobs:
  firefly-pr-compliance-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Validate PR and Branch Name Associated with JIRA Ticket Prefix
      env:
        branch_name: ${{ github.head_ref }}
        pr_title: ${{ github.event.pull_request.title }}
      run: |
        branch_name_lc=$( echo "$branch_name" | awk '{print tolower($0)}' )
        pr_title_lc=$( echo "$pr_title" | awk '{print tolower($0)}' )
        
        if [[ ! "$branch_name_lc" =~ ^infl\-[0-9]{4}.*$ ]]; then
          echo "Your Branch Name: $branch_name"
          echo [COMPLIANCE-ERROR] Please ensure that your branch name starts with the appropriate Jira ticket prefix.
          exit 1
        fi

        if [[ ! "$pr_title_lc" =~ ^infl(\-| )[0-9]{4}.*$ ]]; then
          echo "Your Pull Request Title: $pr_title"
          echo [COMPLIANCE-ERROR] Please ensure that your PR title starts with the appropriate Jira ticket prefix.
          exit 1
        fi