name: demo
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: env
      env:
        myarg_name: "Ahmed's Salah"
        myarg_name2: ${{ 'Ahmed''s Salah' }}
        myarg_num: 12
        myarg_num2: ${{ 12 }}
    - run: env
