name: "my work flow"
on:
  workflow_dispatch: {}
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: ls asdfasdf
    - name: step1
      run: echo "This is step2"
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "Step 1 form Job2"
  
