name: "my work flow"
on:
  workflow_dispatch: {}
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: List
      run: pwd && ls
    - name: Checkout
      uses: actions/checkout@v2
    - name: List Again
      run: ls
