name: demo

on:
  workflow_dispatch:

env:
  DAYS_OF_MONTH: 30
  
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      MYNAME: Ahmed Salah
  call-workflow-passing-data:
    uses: ./.github/workflows/new.yaml
    with:
      personal-name: Ahmed Salah
    secrets:
      envPAT: ${{ secrets.envPAT }}

