name: demo
run-name: ${{ github.event.inputs.name == 'test' && 'DEMO' }} Demo
on:
  workflow_dispatch:
    inputs:
      name:
        description: Name
        required: true
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello world!"
