name: "my work flow"
on:
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: List
      run: pwd && echo ${{ github.token }}
    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v6.0
      with:
        release_branches: main
        github_token: ${{ github.token }}
  
