name: demo
on: ['workflow_dispatch']
jobs:
  demoJob:
    runs-on: ubuntu-latest
    steps:
      - name: Call action
        uses: ahmdsalahme/actions@v2.12
        with:
          command: post-plan
          plan-file: ./temp.json
          workspace: firefly-prod
          args: -l test
      - run: fireflyci version
