name: demo
on: ['workflow_dispatch']
jobs:
  demoJob:
    runs-on: ubuntu-latest
    steps:
      - name: Call action
        uses: ahmdsalahme/actions@v1.2
        with:
         who-to-greet: "Ahmed Salah"
