name: demo
on: ['workflow_dispatch']
jobs:
  demoJob:
    runs-on: ubuntu-latest
    steps:
      - name: Call action
        uses: ahmdsalahme/actions@v2.5
      - run: env
      - run: ls /opt/firefly
