name: demo
on: ['workflow_dispatch']
jobs:
  demoJob:
    runs-on: ubuntu-latest
    steps:
      - name: Call action
        uses: ahmdsalahme/actions@v2.13
        with:
          command: post-plan
          workspace: gofirefly/infrastructure-prod
          args: --timeout 180
      - run: fireflyci version
