name: demo
run-name: ${{ inputs.name }} Demo
on:
  workflow_dispatch:
    inputs:
      name:
        description: Name
        required: true
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello world!"
