name: "my work flow"
on:
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - id: print
      run: pwd
    - run: echo "${{ toJSON(steps.print.outputs) }}"
