name: demo

on:
  workflow_dispatch:

env:
  DAYS_OF_MONTH: 30
  
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      MYNAME: Ahmed Salah
    steps:
    - run: echo "$DAYS_OF_MONTH --  $MYNAME -- $age"
      env:
        age: 23
