name: demo
on: ['workflow_dispatch']
jobs:
  demoJob:
    runs-on: ubuntu-latest
    steps:
      - name: Call action
        uses: ahmdsalahme/actions@v2.9
        with:
          command: post-plan
          plan-file: ./temp.json
      - run: fireflyci version
