# Reusable Workflow
name: new
on:
  workflow_call:
    inputs:
      personal-name:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
    outputs:
      token:
        description: "The first output string"
        value: ${{ jobs.job1.outputs.token }}

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.get-token.outputs.token }}
    steps:
    - run: echo ${{ inputs.personal-name }}
    - run: echo ${{ secrets.envPAT }} > tmp
    - run: cat tmp
    - id: get-token
      run: echo "token=asd123" >> $GITHUB_OUTPUT
