apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: base/base
    repoURL: 'https://github.com/ahmdsalahme/argocd'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}